services:
  # Debt Service Database
  debt-db:
    image: mysql:8.0
    container_name: debt-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: debt_db
    ports:
      - "33063:3306"
    volumes:
      - debt_db_data:/var/lib/mysql
    networks:
      - keuangan-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Debt Service App
  debt-notify-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debt-notify-service
    ports:
      - "8004:8000"
    depends_on:
      debt-db:
        condition: service_healthy
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_KEY=base64:m3o+1Lm3xFyQMU3CLlQH2tM+JTgiYOzqaN86R2IvJJg=
      - APP_DEBUG=true
      - DB_HOST=debt-db
      - DB_PORT=3306
      - DB_DATABASE=debt_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CLIENT=predis
      - REDIS_PREFIX=
      - NOTIFICATIONS_QUEUE=queue:notifications
      - AUTH_SERVICE_URL=http://auth-service:8000
    networks:
      - keuangan-net
    restart: always

  # Debt Service Worker
  debt-notify-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debt-notify-worker
    command: php artisan broker:listen
    depends_on:
      debt-db:
        condition: service_healthy
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_KEY=base64:m3o+1Lm3xFyQMU3CLlQH2tM+JTgiYOzqaN86R2IvJJg=
      - APP_DEBUG=true
      - DB_HOST=debt-db
      - DB_PORT=3306
      - DB_DATABASE=debt_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CLIENT=predis
      - REDIS_PREFIX=
      - NOTIFICATIONS_QUEUE=queue:notifications
      - AUTH_SERVICE_URL=http://auth-service:8000
    networks:
      - keuangan-net
    restart: always

volumes:
  debt_db_data:
    driver: local

networks:
  keuangan-net:
    external: true
    name: keuangan-net
